apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:      
  generateName: example-pipelinerun-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: lint-build-push
  resources:
    - name: repo
      resourceRef: 
        name: robs-tekton-example