apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:    
  name: featurebuild
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: lint-build-push
  resources:
    - name: repo
      resourceRef: 
        name: robs-tekton-example