apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: hadolint
      image: hadolint/hadolint:latest-debian
      workingDir: /workspace/repo
      command:         
        - hadolint                 
      args:               
        - Dockerfile
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:debug
      workingDir: /workspace/repo
      env:
        - name: registry-credentials
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
      args:
        - --dockerfile=Dockerfile
        - --context=/workspace/repo/src
        - --destination=rpassmore/jenkins-test:0.0.1-tekton
        - --no-push